# Generated by Django 4.2.7 on 2023-11-28 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_user_email_user_password_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
