# Generated by Django 4.2.7 on 2023-11-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0006_application_job_userprofile_customuser_delete_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
